# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [armeabi-v7a, arm64-v8a, x86, x86_64]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: download android sdk command line tools
        run: wget https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip 
      - name: make android sdk directory
        run: mkdir sdk
      - name: list directory
        run: ls -alh
      - name: unzip command line tools
        run: unzip commandlinetools-linux-8512546_latest.zip
      - name: list cmdline-tools directory
        run: ls -alh cmdline-tools
      - name: move cmdline-tools to sdk
        run: mv cmdline-tools sdk/
      - name: list sdk directory
        run: ls -alh sdk
      - name: install android-27
        run: echo y | sdk/cmdline-tools/bin/sdkmanager "platforms;android-27" --sdk_root=$(pwd)/sdk 
      - name: install build tools 28.0.2
        run: echo y | sdk/cmdline-tools/bin/sdkmanager "build-tools;28.0.2" --sdk_root=$(pwd)/sdk 
      - name: install ndk
        run: echo y | sdk/cmdline-tools/bin/sdkmanager "ndk;19.2.5345600" --sdk_root=$(pwd)/sdk 
      - name: list sdk directory
        run: ls -alh sdk
      - name: sdk manager 
        run: sdk/cmdline-tools/bin/sdkmanager --list --sdk_root=$(pwd)/sdk
      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x-dev' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
      - name: setup python for android
        run: pip install python-for-android
      - name: setup java8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '8'
      - name: install dependencies
        run: sudo apt-get install -y build-essential ccache git zlib1g-dev libncurses5 libstdc++6 zlib1g unzip ant ccache autoconf libtool libssl-dev
      - name: build python
        run: p4a create --requirements=python3 --blacklist-requirements=sqlite3,android,libffi,openssl --arch ${{ matrix.arch }} --sdk-dir $(pwd)/sdk --ndk-dir $(pwd)/sdk/ndk --android-api 27 --ndk-api 21 --ndk-version r10e
      - name: list python bundle
        run: ls -alh ~/.local/share/python-for-android/
        
      
      
